version: '3.8'
services:
  bot:
    #env_file: configs/.env
    container_name: agent_testing
    build:
        context: .
        #dockerfile: Dockerfile
    #image: node:18-alpine --!!!! вот это не надо было!
    # рабочая директория
    working_dir: /app
    # анонимный том
    # `rw` означает `read/write` - чтение/запись
    volumes:
      - app:/app
      #- app:/app/node_modules
      #- app:/app/logs
    # сервис, от которого зависит работоспособность данного сервиса
#    depends_on:
#      - db
    restart: always
    # команда для запуска сервера для разработки
 #   command: npm run start


volumes:
#    pgdata:
    app:
